stages:
  - build
  - test

# Cache dependencies to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - book_service/.gradle/

build_backend:
  stage: build
  image: gradle:7.4.2-jdk11  # Use a Gradle image with the desired JDK version
  script:
    - cd book_service # Go to book_service
    - gradle clean build  # Use Gradle commands instead of Maven
  artifacts:
    paths:
      - book_service/build/libs/*.jar  # Update the path to the built JAR files

test_backend:
  stage: test
  image: gradle:7.4.2-jdk11  # Use the same Gradle image
  script:
    - cd book_service # Go to book_service
    - gradle test  # Use Gradle to run tests